# Generated by Django 5.1 on 2024-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_show_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la home'),
        ),
    ]
