# Generated by Django 5.1 on 2024-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar enn la home'),
        ),
    ]
