# Generated by Django 5.1 on 2024-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='toc',
            field=models.FileField(blank=True, null=True, upload_to='courses/toc/', verbose_name='Temario'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la home'),
        ),
    ]
