# Generated by Django 5.1 on 2024-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_toc_alter_courses_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images', verbose_name='Portada del curso'),
        ),
    ]
