# Generated by Django 5.1 on 2024-08-12 15:44

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courses_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Portada del curso'),
        ),
    ]
