# Generated by Django 5.1 on 2024-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?'),
        ),
    ]
